### ISSUE TITLE
Inquiring about API Stability and Potential Future Charges

### ISSUE THREAD

**Issue by sobhansajjadi** [sitiusAI/text2image-free#4]
Hello. Thanks for the good API service. I want to add it to my bot but I wanted to ask about its stability. Can I rely on this API and use it or it might stop working soon or become chargeable?

**Comment by Spit-fires** [comment]
As of now im doing my best to keep it stable and free. Due to Deta (I host it on Deta spaces) having a 20s rate limit we are switching servers. After that it will be very stable with proper error code handling.

**Comment by Spit-fires** [comment]
For now its stable but has a 20s timeout. Some unpopular huggingface models will be basically unusable. More popular models will work very stable
