### ISSUE TITLE
Mutual aid

### ISSUE THREAD

**Issue by Metim0l** [sitiusAI/text2image-free#6]
Hello! I am the owner of a large project called VisionCraft: https://github.com/Metim0l/VisionCraft 

I have about 60 different models available. Maybe we can somehow help each other? For example, let's combine our projects into one,  and we will manage them together. I really hope you will write to me in Telegram: https://t.me/Metimol

**Comment by Spit-fires** [comment]
Thank you for this offer but I am sorry to inform you that I have deprecated this due to misuse.  I am currently working on a new version which will take a a very long time.
